### ISSUE TITLE
ncp-nextcloud-exporter: Error during scrape dial tcp: no such host

### ISSUE THREAD

**Issue by kinoegit** [theCalcaholic/ncp-monitoring-dashboard#1]
Installation along the lines of the setup and via ./start.sh went ok so far but https://nextcloud.local:3000 says "server not found" (nextcloud.local is a trusted domain) and ncp-nextcloud-exporter reports:
```
ncp-nextcloud-exporter_1  | level=error msg="Error during scrape: Get \"https://nextcloudpi.local/ocs/v2.php/apps/serverinfo/api/v1/info\": dial tcp: lookup nextcloudpi.local on 127.0.0.11:53: no such host"
```
grafana reports:
```
grafana_1                 | t=2021-10-10T21:18:22+0000 lvl=eror msg="Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins error="open /etc/grafana/provisioning/plugins: no such file or directory"
grafana_1                 | t=2021-10-10T21:18:22+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"
```

NextCloudPi version  v1.40.4
NextCloudPi image    NextCloudPi_10-05-21
distribution         Armbian 21.08.2 Buster \l  on a rock64
automount            yes
USB devices          none
datadir              /var/www/nextcloud/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      6,2G/116G
rootfs usage         6,2G/116G
swapfile             /var/swap
dbdir                /var/lib/mysql
Nextcloud check      ok
Nextcloud version    21.0.4.1
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
HPB service          up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open

**Comment by theCalcaholic** [comment]
The dashboard should be reachable at https://localhost:3000, not http://nextcloudpi.local:3000

Can you please try that?

**Comment by kinoegit** [comment]
with https://localhost:3000 no connection either

**Comment by theCalcaholic** [comment]
@kinoegit I just stumbled about the solution. It should be http://localhost:3000 (not https). Sorry for being blind :see_no_evil:
