### ISSUE TITLE
error in: start.sh

### ISSUE THREAD

**Issue by Zakspeed** [theCalcaholic/ncp-monitoring-dashboard#2]
UbuntuSRV ~/ncp-monitoring-dashboard$ sh start.sh
start.sh: 35: [[: not found
start.sh: 43: .: .env: not found

**Comment by Zakspeed** [comment]
1º git clone https://github.com/theCalcaholic/ncp-monitoring-dashboard

**Comment by theCalcaholic** [comment]
You need to execute the script with bash, not sh.

Try `bash start.sh` or simply `./start.sh`
